# Generated by Django 2.1.4 on 2019-03-27 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20190327_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_colheita',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 18, 7, 4, 415088)),
        ),
    ]
